//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proyecto_final_Sistema_de_Agencia_de_Tours
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AgenciaToursDBEntities : DbContext
    {
        public AgenciaToursDBEntities()
            : base("name=AgenciaToursDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Destino> Destino { get; set; }
        public virtual DbSet<Pais> Pais { get; set; }
        public virtual DbSet<Tour> Tour { get; set; }
    }
}
