//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proyecto_final_Sistema_de_Agencia_de_Tours
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tour
    {
        public string TourId { get; set; }
        public string Nombre { get; set; }
        public int PaisId { get; set; }
        public int DestinoId { get; set; }
        public System.DateTime Fecha { get; set; }
        public System.TimeSpan Hora { get; set; }
        public decimal Precio { get; set; }
        public decimal ITBIS { get; set; }
        public int DuracionDias { get; set; }
        public int DuracionHoras { get; set; }
        public System.DateTime FechaHoraFin { get; set; }
        public string Estado { get; set; }
    
        public virtual Destino Destino { get; set; }
        public virtual Pais Pais { get; set; }
    }
}
